LRNG: fix compilation under 4.19 kernel
Link: [1] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-01-remove_compat_ioctl.patch
      [2] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-03-arch_random_early.patch
      [3] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-04-net_rand_state.patch
      [4] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-05-kzfree.patch
      [5] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-06-chacha20_block_invocation.patch#L56
      [6] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-07-remove_vla_hash.patch
      [7] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-08-sha-includes.patch
      [8] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-13-rand-initialize-early-initcall.patch
      [9] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-14-lrng-linux-preempt-include.patch
      [11] https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-15-chacha_constants.patch

Note: Don't apply https://github.com/smuellerDD/lrng/blob/master/backports/v43-4.19/v43-06-chacha20_block_invocation.patch into
      a kernel tree which has merged Android Common Kernel in.

* Change struct chacha20_(block|state) chacha20 to lrng_chacha20 to avoid
  linker error "ld.lld: error: duplicate symbol: chacha20"